application: udacity-hw7-final2
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: wiki.app

libraries:
- name: jinja2
  version: latest
